import { Footer } from "@/widgets/footer";
import { Navbar } from "@/widgets/navbar";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { NoorThemeProvider, type ThemeConfig } from "noor-ui";
import "./globals.css";
import { type ReactNode } from "react";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const themeConfig: ThemeConfig = {
    components: {
      // button: {
      //   defaultProps: {
      //     variant: "outlined",
      //     size: "md",
      //     color: "primary",
      //     fullWidth: false,
      //     className: "",
      //   },
      //   valid: {
      //     variants: ["filled", "outlined", "text", "gradient"],
      //     sizes: ["sm", "md", "lg"],
      //     // colors: ["blue", "red", "green", "gray"],
      //   },
      //   styles: {
      //     base: {
      //       initial: {
      //         borderRadius: "rounded-lg",
      //         fontWeight: "font-medium",
      //       },
      //       fullWidth: {
      //         width: "w-full",
      //       },
      //     },
      //     sizes: {
      //       sm: { padding: "px-2 py-1.5", fontSize: "text-sm" },
      //       md: { padding: "px-4 py-2", fontSize: "text-base" },
      //       lg: { padding: "px-6 py-3", fontSize: "text-lg" },
      //     },
      //     variants: {
      //       filled: { backgroundColor: "bg-blue-500", color: "text-white" },
      //       outlined: {
      //         border: "border border-blue-500",
      //         color: "text-blue-500",
      //       },
      //       text: { color: "text-blue-500" },
      //       gradient: {
      //         background: "bg-gradient-to-r from-blue-500 to-purple-500",
      //       },
      //     },
      //   },
      // },
    },
  };

  return (
    <html lang="en">
      <NoorThemeProvider theme={themeConfig} defaultMode={"dark"}>
        <body
          className={`${robotoSans.variable} dark:bg-black dark:text-white bg-white text:black antialiased`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </NoorThemeProvider>
    </html>
  );
}
