import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NoorThemeProvider, type ThemeConfig } from "noor-ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeConfig: ThemeConfig = {
    components: {
      // button: {
      //   defaultProps: {
      //     variant: "outlined",
      //     size: "md",
      //     color: "primary",
      //     fullWidth: false,
      //     className: "",
      //   },
      //   valid: {
      //     variants: ["filled", "outlined", "text", "gradient"],
      //     sizes: ["sm", "md", "lg"],
      //     // colors: ["blue", "red", "green", "gray"],
      //   },
      //   styles: {
      //     base: {
      //       initial: {
      //         borderRadius: "rounded-lg",
      //         fontWeight: "font-medium",
      //       },
      //       fullWidth: {
      //         width: "w-full",
      //       },
      //     },
      //     sizes: {
      //       sm: { padding: "px-2 py-1.5", fontSize: "text-sm" },
      //       md: { padding: "px-4 py-2", fontSize: "text-base" },
      //       lg: { padding: "px-6 py-3", fontSize: "text-lg" },
      //     },
      //     variants: {
      //       filled: { backgroundColor: "bg-blue-500", color: "text-white" },
      //       outlined: {
      //         border: "border border-blue-500",
      //         color: "text-blue-500",
      //       },
      //       text: { color: "text-blue-500" },
      //       gradient: {
      //         background: "bg-gradient-to-r from-blue-500 to-purple-500",
      //       },
      //     },
      //   },
      // },
    },
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NoorThemeProvider theme={themeConfig} defaultMode={"dark"}>
          {children}
        </NoorThemeProvider>
      </body>
    </html>
  );
}
