export const inputFilled: object = {
  primary: {
    background: "bg-[var(--noor-color-primary)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-primary)]/10 focus:ring-2 focus:ring-[var(--noor-color-primary)]/20",
    hover: "hover:bg-[var(--noor-color-primary)]/8",
  },
  secondary: {
    background: "bg-[var(--noor-color-secondary)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-secondary)]/10 focus:ring-2 focus:ring-[var(--noor-color-secondary)]/20",
    hover: "hover:bg-[var(--noor-color-secondary)]/8",
  },
  success: {
    background: "bg-[var(--noor-color-success)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-success)]/10 focus:ring-2 focus:ring-[var(--noor-color-success)]/20",
    hover: "hover:bg-[var(--noor-color-success)]/8",
  },
  error: {
    background: "bg-[var(--noor-color-danger)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-danger)]/10 focus:ring-2 focus:ring-[var(--noor-color-danger)]/20",
    hover: "hover:bg-[var(--noor-color-danger)]/8",
  },
  info: {
    background: "bg-[var(--noor-color-info)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-info)]/10 focus:ring-2 focus:ring-[var(--noor-color-info)]/20",
    hover: "hover:bg-[var(--noor-color-info)]/8",
  },
  warning: {
    background: "bg-[var(--noor-color-warning)]/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-[var(--noor-color-warning)]/10 focus:ring-2 focus:ring-[var(--noor-color-warning)]/20",
    hover: "hover:bg-[var(--noor-color-warning)]/8",
  },
  white: {
    background: "bg-white/5",
    color: "text-gray-900",
    border: "border-0",
    placeholder: "placeholder-gray-500",
    focus: "focus:bg-white/10 focus:ring-2 focus:ring-white/20",
    hover: "hover:bg-white/8",
  },
};
