export const iconButtonOutlined: object = {
  primary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-primary)]",
    border: "border border-[var(--noor-color-primary)]",
    shadow: "shadow-sm shadow-[var(--noor-color-primary)]/10",
    hover: "hover:bg-[var(--noor-color-primary)]/10",
    focus: "focus:bg-[var(--noor-color-primary)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-primary)]/20 active:shadow-none",
  },
  secondary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-secondary)]",
    border: "border border-[var(--noor-color-secondary)]",
    shadow: "shadow-sm shadow-[var(--noor-color-secondary)]/10",
    hover: "hover:bg-[var(--noor-color-secondary)]/10",
    focus: "focus:bg-[var(--noor-color-secondary)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-secondary)]/20 active:shadow-none",
  },
  success: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-success)]",
    border: "border border-[var(--noor-color-success)]",
    shadow: "shadow-sm shadow-[var(--noor-color-success)]/10",
    hover: "hover:bg-[var(--noor-color-success)]/10",
    focus: "focus:bg-[var(--noor-color-success)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-success)]/20 active:shadow-none",
  },
  error: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-danger)]",
    border: "border border-[var(--noor-color-danger)]",
    shadow: "shadow-sm shadow-[var(--noor-color-danger)]/10",
    hover: "hover:bg-[var(--noor-color-danger)]/10",
    focus: "focus:bg-[var(--noor-color-danger)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-danger)]/20 active:shadow-none",
  },
  info: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-info)]",
    border: "border border-[var(--noor-color-info)]",
    shadow: "shadow-sm shadow-[var(--noor-color-info)]/10",
    hover: "hover:bg-[var(--noor-color-info)]/10",
    focus: "focus:bg-[var(--noor-color-info)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-info)]/20 active:shadow-none",
  },
  warning: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-warning)]",
    border: "border border-[var(--noor-color-warning)]",
    shadow: "shadow-sm shadow-[var(--noor-color-warning)]/10",
    hover: "hover:bg-[var(--noor-color-warning)]/10",
    focus: "focus:bg-[var(--noor-color-warning)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-warning)]/20 active:shadow-none",
  },
};
