export const iconButtonFilled: object = {
  primary: {
    background: "bg-[var(--noor-color-primary)]",
    color: "text-[var(--noor-color-primary-contrast)]",
    hover: "hover:bg-[var(--noor-color-primary)]/80",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  secondary: {
    background: "bg-[var(--noor-color-secondary)]",
    color: "text-[var(--noor-color-secondary-contrast)]",
    hover: "hover:bg-[var(--noor-color-secondary)]/90",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  success: {
    background: "bg-[var(--noor-color-success)]",
    color: "text-white",
    hover: "hover:bg-[var(--noor-color-success)]/90",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  error: {
    background: "bg-[var(--noor-color-danger)]",
    color: "text-white",
    hover: "hover:bg-[var(--noor-color-danger)]/90",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  info: {
    background: "bg-[var(--noor-color-info)]",
    color: "text-white",
    hover: "hover:bg-[var(--noor-color-info)]/90",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  warning: {
    background: "bg-[var(--noor-color-warning)]",
    color: "text-white",
    hover: "hover:bg-[var(--noor-color-warning)]/90",
    focus: "focus:opacity-85 focus:shadow-none",
    active: "active:opacity-90 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
};
