export const iconButtonOutlined: object = {
  primary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-primary)]",
    border: "border border-[var(--noor-color-primary)]",
    hover: "hover:bg-[var(--noor-color-primary)]/10 hover:border-[var(--noor-color-primary)]/90",
    focus: "focus:bg-[var(--noor-color-primary)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-primary)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  secondary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-secondary)]",
    border: "border border-[var(--noor-color-secondary)]",
    hover: "hover:bg-[var(--noor-color-secondary)]/10 hover:border-[var(--noor-color-secondary)]/90",
    focus: "focus:bg-[var(--noor-color-secondary)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-secondary)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  success: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-success)]",
    border: "border border-[var(--noor-color-success)]",
    hover: "hover:bg-[var(--noor-color-success)]/10 hover:border-[var(--noor-color-success)]/90",
    focus: "focus:bg-[var(--noor-color-success)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-success)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  error: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-danger)]",
    border: "border border-[var(--noor-color-danger)]",
    hover: "hover:bg-[var(--noor-color-danger)]/10 hover:border-[var(--noor-color-danger)]/90",
    focus: "focus:bg-[var(--noor-color-danger)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-danger)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  info: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-info)]",
    border: "border border-[var(--noor-color-info)]",
    hover: "hover:bg-[var(--noor-color-info)]/10 hover:border-[var(--noor-color-info)]/90",
    focus: "focus:bg-[var(--noor-color-info)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-info)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  warning: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-warning)]",
    border: "border border-[var(--noor-color-warning)]",
    hover: "hover:bg-[var(--noor-color-warning)]/10 hover:border-[var(--noor-color-warning)]/90",
    focus: "focus:bg-[var(--noor-color-warning)]/10 focus:shadow-none",
    active: "active:bg-[var(--noor-color-warning)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
};
