export const iconButtonGradient: object = {
  primary: {
    background: "bg-gradient-to-r from-[var(--noor-color-primary)] to-[var(--noor-color-primary)]/80",
    color: "text-[var(--noor-color-primary-contrast)]",
    shadow: "shadow-md shadow-[var(--noor-color-primary)]/20",
    hover: "hover:from-[var(--noor-color-primary)]/90 hover:to-[var(--noor-color-primary)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  secondary: {
    background: "bg-gradient-to-r from-[var(--noor-color-secondary)] to-[var(--noor-color-secondary)]/80",
    color: "text-[var(--noor-color-secondary-contrast)]",
    shadow: "shadow-md shadow-[var(--noor-color-secondary)]/20",
    hover: "hover:from-[var(--noor-color-secondary)]/90 hover:to-[var(--noor-color-secondary)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  success: {
    background: "bg-gradient-to-r from-[var(--noor-color-success)] to-[var(--noor-color-success)]/80",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-success)]/20",
    hover: "hover:from-[var(--noor-color-success)]/90 hover:to-[var(--noor-color-success)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  error: {
    background: "bg-gradient-to-r from-[var(--noor-color-danger)] to-[var(--noor-color-danger)]/80",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-danger)]/20",
    hover: "hover:from-[var(--noor-color-danger)]/90 hover:to-[var(--noor-color-danger)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  info: {
    background: "bg-gradient-to-r from-[var(--noor-color-info)] to-[var(--noor-color-info)]/80",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-info)]/20",
    hover: "hover:from-[var(--noor-color-info)]/90 hover:to-[var(--noor-color-info)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  warning: {
    background: "bg-gradient-to-r from-[var(--noor-color-warning)] to-[var(--noor-color-warning)]/80",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-warning)]/20",
    hover: "hover:from-[var(--noor-color-warning)]/90 hover:to-[var(--noor-color-warning)]/70",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
};
