export const iconButtonText: object = {
  primary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-primary)]",
    hover: "hover:bg-[var(--noor-color-primary)]/10",
    focus: "focus:bg-[var(--noor-color-primary)]/10 focus:ring focus:ring-[var(--noor-color-primary)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-primary)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  secondary: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-secondary)]",
    hover: "hover:bg-[var(--noor-color-secondary)]/10",
    focus: "focus:bg-[var(--noor-color-secondary)]/10 focus:ring focus:ring-[var(--noor-color-secondary)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-secondary)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  success: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-success)]",
    hover: "hover:bg-[var(--noor-color-success)]/10",
    focus: "focus:bg-[var(--noor-color-success)]/10 focus:ring focus:ring-[var(--noor-color-success)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-success)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  error: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-danger)]",
    hover: "hover:bg-[var(--noor-color-danger)]/10",
    focus: "focus:bg-[var(--noor-color-danger)]/10 focus:ring focus:ring-[var(--noor-color-danger)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-danger)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  info: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-info)]",
    hover: "hover:bg-[var(--noor-color-info)]/10",
    focus: "focus:bg-[var(--noor-color-info)]/10 focus:ring focus:ring-[var(--noor-color-info)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-info)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
  warning: {
    background: "bg-transparent",
    color: "text-[var(--noor-color-warning)]",
    hover: "hover:bg-[var(--noor-color-warning)]/10",
    focus: "focus:bg-[var(--noor-color-warning)]/10 focus:ring focus:ring-[var(--noor-color-warning)]/40 focus:shadow-none",
    active: "active:bg-[var(--noor-color-warning)]/20 active:scale-90 active:shadow-none",
    transition: "transition duration-150 ease-in-out",
  },
};
