export const buttonFilled: object = {
  primary: {
    background: "bg-[var(--noor-color-primary)]",
    color: "text-[var(--noor-color-primary-contrast)]",
    shadow: "shadow-md shadow-[var(--noor-color-primary)]/10",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-primary)]/20",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  secondary: {
    background: "bg-[var(--noor-color-secondary)]",
    color: "text-[var(--noor-color-secondary-contrast)]",
    shadow: "shadow-md shadow-[var(--noor-color-secondary)]/10",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-secondary)]/20",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  success: {
    background: "bg-[var(--noor-color-success)]",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-success)]/20",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-success)]/40",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  error: {
    background: "bg-[var(--noor-color-danger)]",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-danger)]/20",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-danger)]/40",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  info: {
    background: "bg-[var(--noor-color-info)]",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-info)]/20",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-info)]/40",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  warning: {
    background: "bg-[var(--noor-color-warning)]",
    color: "text-white",
    shadow: "shadow-md shadow-[var(--noor-color-warning)]/20",
    hover: "hover:shadow-lg hover:shadow-[var(--noor-color-warning)]/40",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
};
