export const buttonOutlined: object = {
  primary: {
    border: "border border-[var(--noor-color-primary)]",
    color: "text-[var(--noor-color-primary)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-primary)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
  secondary: {
    border: "border border-[var(--noor-color-secondary)]",
    color: "text-[var(--noor-color-secondary)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-secondary)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
  success: {
    border: "border border-[var(--noor-color-success)]",
    color: "text-[var(--noor-color-success)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-success)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
  error: {
    border: "border border-[var(--noor-color-danger)]",
    color: "text-[var(--noor-color-danger)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-danger)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
  info: {
    border: "border border-[var(--noor-color-info)]",
    color: "text-[var(--noor-color-info)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-info)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
  warning: {
    border: "border border-[var(--noor-color-warning)]",
    color: "text-[var(--noor-color-warning)]",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-[var(--noor-color-warning)]/50",
    active: "active:opacity-90 active:scale-95",
    transition: "transition duration-150 ease-in-out",
  },
};
